### ISSUE TITLE
Verilating problems

### ISSUE THREAD

**Issue by liuyuxivapor** [ToNi3141/Rasterix#40]
Reporting errors like `Unsupported: Parameters in functions` when Verilating `make`.
By the way, how could I simulate an lcd like ILI9341 along with my own SOC? I v checked Unittest but it seems not to work well. Thanks a lot!

**Comment by ToNi3141** [comment]
Which verilator version are you using? At least I never got this message with 4.220 and under osx. Unfortunately I didn't try other operating systems or other versions.

The unittest for the ILI9341 is just testing the initialization sequence of the display and if it can transfer data from the AXIS to the display. The ILI9341 itself will just stream the data from the AXIS to the display.
The simulation which I used to draw a picture on the screen utilizes directly the AXIS stream from the color buffer. The functionality is implemented in `VerilatorBusConnecter.hpp`. I check in the `clk()` method if I got a valid beat from the color buffer AXIS and store it into an array which is later displayed. Theoretically you can use a equal strategy with the ILI9341.
Hopefully that helps.
